### ISSUE TITLE
Support for newest Saleor version?

### ISSUE THREAD

**Issue by joeyjurjens** [divio/saleor-boilerplate#9]
Hello, is it possible to update this boilerplate to the newest version of Saleor?
As the newest Saleor has allot of improvements, especially to the dashboard.

I think it should be using this then: https://github.com/mirumee/saleor-platform
As the dashboard, storefront etc is separated now.

Thanks

**Comment by FinalAngel** [comment]
Hello @joeyjurjens , there's currently no plan from our end to update the boilerplate as the update process is basically copying the files to your project manually and very error prone. You can find hints on how to do that yourself from this file:

https://github.com/divio/saleor-boilerplate/blob/master/update_saleor.sh

**Comment by joeyjurjens** [comment]
I saw the script, though I don't think that's the case anymore with the new saleor?
As the new saleor itself no longer includes the storefront and dashboard.

However, if then there's still no plan in upgrading it, I'll try to create a boilerplate for the newest version myself.
